/*==============================================
  Task 1: Running code
  Run the code that creates a table object called System_Values_Insert

  Testing
  ----------
  -- verify table exists, but it doesnt verify the column names and datatypes
SELECT table_name FROM user_tables WHERE table_name = UPPER('System_Values');

  Marking 
  ----------
  1 for running the code to create System_Values table

  Total points: 1
===============================================*/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE System_Values CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/


CREATE TABLE System_Values (
  ID        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Key       VARCHAR2(100) NOT NULL,
  Operation VARCHAR2(50),
  Value     VARCHAR2(200)
);

ALTER TABLE System_Values
  ADD CONSTRAINT uq_system_values_key UNIQUE (Key);

