
/*===============================================

 Task 12: Table Invalid_Login

We need a way of logging and tracking invalid login activities for security or auditing purposes. 
The command itself produces no output messages; any success or error responses are managed by the database system.

Create  SQL statement to create a table called Invalid_Login that stores information about failed login attempts. 
It includes an automatically generated numeric ID as the primary key, a Username field to record the user involved, 
an Attempt_Date field that automatically captures the current system timestamp when a record is inserted, 
and a Reason field to describe why the login failed. 

Testing
-------------
-- verify table exists, but it doesnt verify the column names and datatypes
SELECT table_name FROM user_tables WHERE table_name = UPPER('invalid_login');

Marking 
-------------

 2 for correct object and table name invalid_login
 2 for correct variable names
 2 for data types
 1 for primary key that is autogenerated
 1 for putting default value on attempted_date to be now

Total Marks: 8
==========================================*/


